const preguntasMMPI2 = [

{id:1,texto:"Me gustan las revistas de mecánica."},
{id:2,texto:"Tengo buen apetito."},
{id:3,texto:"Casi siempre me levanto por las mañanas descansado y como nuevo."},
{id:4,texto:"Creo que me gustaría trabajar como bibliotecario."},
{id:5,texto:"El ruido me despierta fácilmente."},
{id:6,texto:"Mi padre es un buen hombre (o lo fue en caso de haber fallecido)."},
{id:7,texto:"Me gusta leer artículos sobre crímenes en los periódicos."},
{id:8,texto:"Normalmente tengo bastante calientes los pies y las manos."},
{id:9,texto:"En mi vida diaria hay muchas cosas que me resultan interesantes."},
{id:10,texto:"Actualmente, tengo tanta capacidad de trabajo como antes."},
{id:11,texto:"La mayor parte del tiempo me parece tener un nudo en la garganta."},
{id:12,texto:"Mi vida sexual es satisfactoria."},
{id:13,texto:"La gente debería intentar comprender sus sueños y guiarse por ellos o tomarlos como avisos."},
{id:14,texto:"Me divierten las historias de detectives y de misterio."},
{id:15,texto:"Trabajo bajo una tensión muy grande."},
{id:16,texto:"De vez en cuando pienso en cosas demasiado malas como para hablar de ellas."},
{id:17,texto:"Estoy seguro de que la vida es dura para mí."},
{id:18,texto:"Sufro ataques de náuseas y vómitos."},
{id:19,texto:"Cuando acepto un nuevo empleo, me gusta descubrir a quien debo “caerle bien”."},
{id:20,texto:"Muy rara vez sufro de constipación (sequedad de vientre)."},
{id:21,texto:"A veces he deseado muchísimo abandonar el hogar."},
{id:22,texto:"Nadie parece comprenderme."},
{id:23,texto:"A veces tengo accesos de risa y llanto que no puedo controlar."},
{id:24,texto:"A veces estoy poseído por espíritus diabólicos."},
{id:25,texto:"Me gustaría ser cantante."},
{id:26,texto:"Cuando estoy en dificultades o problemas creo que lo mejor es callarme."},
{id:27,texto:"Cuando alguien me hace algún daño, siento deseos de devolvérselo si me es posible, y esto, por cuestión de principios."},
{id:28,texto:"Varias veces a la semana me molesta la acidez de estómago."},
{id:29,texto:"A veces siento deseos de maldecir."},
{id:30,texto:"A menudo tengo pesadillas."},
{id:31,texto:"Me cuesta bastante concentrarme en una tarea o trabajo."},
{id:32,texto:"He tenido muy peculiares y extrañas experiencias."},
{id:33,texto:"Raras veces me preocupo por mi salud."},
{id:34,texto:"Nunca me he visto en dificultades a causa de mi conducta sexual."},
{id:35,texto:"Durante algún tiempo, cuando era joven, participé en pequeños robos."},
{id:36,texto:"Tengo tos la mayor parte del tiempo."},
{id:37,texto:"A veces siento deseos de romper cosas."},
{id:38,texto:"He tenido períodos de días, semanas o meses en los que no podía preocuparme por las cosas, porque no tenía ánimo para nada."},
{id:39,texto:"Mi sueño es irregular, inquieto."},
{id:40,texto:"La mayor parte del tiempo parece dolerme la cabeza por todas partes."},
{id:41,texto:"No digo siempre la verdad."},
{id:42,texto:"Si los demás no la hubieran tomado conmigo, hubiese tenido más éxito."},
{id:43,texto:"Mis razonamientos son ahora mejores que nunca."},
{id:44,texto:"Una vez a la semana, o más a menudo, siento calor por todo el cuerpo sin causa aparente."},
{id:45,texto:"Tengo tan buena salud física como la mayor parte de mis amigos."},
{id:46,texto:"Prefiero hacerme el desentendido con amigos del colegio o personas conocidas que no veo desde hace tiempo, a menos que ellos me hablen primero."},
{id:47,texto:"Casi nunca he sufrido de dolores en el pecho o en el corazón."},
{id:48,texto:"En muchas ocasiones me gustaría más sentarme y soñar despierto que hacer cualquier cosa."},
{id:49,texto:"Soy una persona sociable."},
{id:50,texto:"A menudo he recibido órdenes de alguien que no sabía tanto como yo."},
{id:51,texto:"No leo diariamente todos los artículos principales del diario."},
{id:52,texto:"No he llevado un tipo de vida adecuado y normal."},
{id:53,texto:"A menudo algunas partes de mi cuerpo tienen sensaciones de hormigueo, quemazón, picazón o bien de quedarse dormidas»."},
{id:54,texto:"A mi familia no le gusta el trabajo que he elegido (o el trabajo que pienso elegir para mi futuro)."},
{id:55,texto:"Algunas veces persisto en una cosa o tema hasta que los demás pierden la paciencia conmigo."},
{id:56,texto:"Me gustaría ser tan feliz como parecen ser los otros."},
{id:57,texto:"Muy raras veces siento dolor en la nuca."},
{id:58,texto:"Pienso que una gran mayoría de gente exagera sus desgracias para lograr la simpatía y ayuda de los demás."},
{id:59,texto:"Tengo molestias en la boca del estómago casi a diario."},
{id:60,texto:"Cuando estoy con gente escucho cosas extrañas."},
{id:61,texto:"Soy una persona importante."},
{id:62,texto:"A menudo he deseado ser mujer. (O si Ud. es mujer: nunca me ha molestado ser mujer)."},
{id:63,texto:"Mis sentimientos no son heridos con facilidad."},
{id:64,texto:"Me gusta leer novelas de amor."},
{id:65,texto:"La mayor parte del tiempo siento melancolía."},
{id:66,texto:"Se viviría mejor sin leyes."},
{id:67,texto:"Me gusta la poesía."},
{id:68,texto:"A veces hago rabiar (jugando) a los animales."},
{id:69,texto:"Creo que me gustaría el trabajo de guardabosques."},
{id:70,texto:"En una discusión o debate, me dejo vencer fácilmente."},
{id:71,texto:"En el momento actual me es difícil tener la esperanza de llegar a ser alguien."},
{id:72,texto:"A veces mi alma abandona mi cuerpo."},
{id:73,texto:"Decididamente no tengo confianza en mí mismo."},
{id:74,texto:"Me gustaría ser florista."},
{id:75,texto:"Normalmente siento que la vida vale la pena vivirla."},
{id:76,texto:"Se necesita discutir mucho para convencer a la mayor parte de la gente de la verdad."},
{id:77,texto:"De vez en cuando dejo para mañana lo que debería hacer hoy."},
{id:78,texto:"Le agrado a la mayor parte de la gente que me conoce."},
{id:79,texto:"No me importa que se diviertan haciéndome bromas."},
{id:80,texto:"Me gustaría ser enfermero."},
{id:81,texto:"Creo que la mayor parte de la gente mentiría para conseguir lo que busca."},
{id:82,texto:"Hago muchas cosas de las que me arrepiento luego. (Me arrepiento de más cosas o con más frecuencia que otras personas.)"},
{id:83,texto:"Tengo pocas peleas con las personas de mi familia."},
{id:84,texto:"Siendo joven me echaron de clase, una o más veces, por portarme mal."},
{id:85,texto:"A veces siento grandes deseos de hacer algo dañino o chocante."},
{id:86,texto:"Me gusta asistir a reuniones o fiestas donde hay mucha alegría y ruido."},
{id:87,texto:"Me he encontrado con problemas tan llenos de posibilidades que no he podido llegar a una decisión."},
{id:88,texto:"Creo que las mujeres deben tener tanta libertad sexual como los hombres."},
{id:89,texto:"Las luchas más encarnizadas las tengo conmigo mismo."},
{id:90,texto:"Yo quiero mucho a mi padre. (O lo quise, si falleció)."},
{id:91,texto:"Tengo pocas o ninguna molestia a causa de espasmos o contracciones musculares."},
{id:92,texto:"No parece importarme lo que me suceda."},
{id:93,texto:"A veces, cuando no me siento bien, estoy irritable."},
{id:94,texto:"La mayor parte del tiempo me parece haber hecho algo malo o equivocado."},
{id:95,texto:"Soy feliz la mayor parte del tiempo."},
{id:96,texto:"Veo a mi alrededor cosas, animales o personas que otros no ven."},
{id:97,texto:"Parece como si la mayor parte del tiempo tuviera la cabeza cargada o llena de ruidos."},
{id:98,texto:"Hay algunas personas tan mandonas que me dan ganas de hacer lo contrario de lo que quieren, aunque sepa que tienen razón."},
{id:99,texto:"Alguien me la tiene jurada."},
{id:100,texto:"Nunca he hecho algo peligroso sólo por el placer de hacerlo."},
{id:101,texto:"A menudo siento como si tuviera una venda puesta fuertemente alrededor de mi cabeza."},
{id:102,texto:"Alguna vez me enojo."},
{id:103,texto:"Me divierte más un juego cuando yo apuesto."},
{id:104,texto:"La mayoría de la gente es honrada por temor a ser descubierta."},
{id:105,texto:"En el colegio, algunas veces, fui enviado al director a causa de mi mala conducta."},
{id:106,texto:"Mi manera de hablar es como siempre (ni más rápida, ni más lenta, ni más atropellada, no tengo carraspera"},
{id:107,texto:"Mis modales en la mesa no son tan correctos en mi casa como cuando salgo a comer afuera."},
{id:108,texto:"Cualquier persona capacitada y dispuesta a trabajar fuerte, tiene muchas probabilidades de tener éxito."},
{id:109,texto:"Me parece ser tan capaz y despierto como la mayor parte de los que me rodean."},
{id:110,texto:"Para no perder un beneficio o ventaja, la mayoría de la gente está dispuesta a hacer cualquier cosa."},
{id:111,texto:"Tengo bastantes trastornos digestivos."},
{id:112,texto:"Me gustan el teatro y el cine."},
{id:113,texto:"Sé quien es el responsable de muchos de mis problemas."},
{id:114,texto:"A veces me siento tan atraído por las cosas de otros (zapatos. reloj), que tengo ganas de robarlas."},
{id:115,texto:"Ver sangre no me da miedo ni me hace mal."},
{id:116,texto:"Frecuentemente no puedo comprender por que he estado tan gruñón y malhumorado."},
{id:117,texto:"Nunca he vomitado sangre o sangrado al toser."},
{id:118,texto:"No me preocupa contraer una enfermedad."},
{id:119,texto:"Me gusta recoger flores o cultivar plantas en casa."},
{id:120,texto:"Frecuentemente encuentro necesario defender lo que es justo."},
{id:121,texto:"Nunca me he entregado a prácticas sexuales fuera de lo común."},
{id:122,texto:"A veces mi pensamiento ha ido más rápido y por delante de mis palabras."},
{id:123,texto:"Si pudiera entrar en un espectáculo sin pagar y estuviera seguro de no ser visto, probablemente lo haría."},
{id:124,texto:"Generalmente me pregunto qué razón oculta puede tener otra persona cuando me hace un favor."},
{id:125,texto:"Creo que mi vida hogareña es tan agradable como la de mucha gente que conozco."},
{id:126,texto:"Es necesario reforzar las leyes vigentes."},
{id:127,texto:"Me hieren profundamente las críticas y los retos."},
{id:128,texto:"Me gusta cocinar."},
{id:129,texto:"Mi conducta es ampliamente controlada por las costumbres que me rodean."},
{id:130,texto:"A veces siento que verdaderamente soy un inútil."},
{id:131,texto:"Cuando era joven pertenecía a una banda que intentaba mantenerse unida como “carne y uña”."},
{id:132,texto:"Creo en la vida del más allá."},
{id:133,texto:"Me gustaría ser soldado."},
{id:134,texto:"A veces siento deseos de tomarme a puñetazos con alguien."},
{id:135,texto:"Frecuentemente he perdido o desaprovechado cosas por no saber decidirme a tiempo."},
{id:136,texto:"Me molesta que me pidan consejo o que me interrumpan cuan do estoy trabajando en algo importante."},
{id:137,texto:"Solía llevar un diario personal."},
{id:138,texto:"Creo que se trama algo contra mí."},
{id:139,texto:"En un juego o partida suelo más ganar que perder."},
{id:140,texto:"Casi todas las noches me duermo sin ideas o pensamientos molestos."},
{id:141,texto:"Durante los últimos años he estado sano casi siempre."},
{id:142,texto:"Nunca he tenido un ataque o convulsión."},
{id:143,texto:"Ahora no estoy subiendo ni bajando de peso."},
{id:144,texto:"Creo que me siguen."},
{id:145,texto:"Creo que frecuentemente he sido castigado sin causa."},
{id:146,texto:"Lloro con facilidad."},
{id:147,texto:"Actualmente no comprendo lo que leo con la facilidad que tenía antes."},
{id:148,texto:"Nunca me he sentido mejor que ahora."},
{id:149,texto:"A veces siento dolores en la parte superior de la cabeza."},
{id:150,texto:"A veces siento que tengo que hacerme daño a mí mismo o a alguien."},
{id:151,texto:"Me molesta que alguien se haya burlado tan inteligentemente de mí que yo haya tenido que admitir que lo logró."},
{id:152,texto:"No me canso fácilmente."},
{id:153,texto:"Me gusta conocer alguna gente importante porque esto me hace sentir importante."},
{id:154,texto:"Siento miedo cuando miro hacia abajo desde un lugar alto."},
{id:155,texto:"No me sentiría nervioso si algún familiar tuviera problemas con la ley."},
{id:156,texto:"Sólo me siento feliz cuando viajo de un lado para otro."},
{id:157,texto:"Me es indiferente lo que los demás piensen de mí."},
{id:158,texto:"Me siento incómodo cuando tengo que hacer una payasada en una reunión, incluso aunque otros la estén haciendo."},
{id:159,texto:"Nunca he tenido un desmayo o desvanecimiento."},
{id:160,texto:"Me gustaba ir al colegio."},
{id:161,texto:"Frecuentemente tengo que esforzarme para no demostrar que soy tímido."},
{id:162,texto:"Alguien ha intentando envenenarme."},
{id:163,texto:"Las serpientes no me dan mucho miedo."},
{id:164,texto:"Nunca o rara vez tengo mareos."},
{id:165,texto:"Mi memoria parece ser normal."},
{id:166,texto:"Me preocupan los temas sexuales."},
{id:167,texto:"Me es difícil entablar una conversación cuando recién conozco a alguien."},
{id:168,texto:"He tenido épocas durante las cuales he realizado actividades que luego no recordaba haber hecho."},
{id:169,texto:"Cuando estoy aburrido me gusta promover algo excitante."},
{id:170,texto:"Tengo miedo de volverme loco."},
{id:171,texto:"Estoy en contra de dar dinero a los mendigos."},
{id:172,texto:"Frecuentemente noto temblar mis manos cuando intento hacer algo."},
{id:173,texto:"Puedo leer mucho tiempo sin que se me canse la vista."},
{id:174,texto:"Me gusta leer y estudiar acerca de lo que estoy trabajando."},
{id:175,texto:"Siento debilidad general la mayor parte del tiempo."},
{id:176,texto:"Muy pocas veces me duele la cabeza."},
{id:177,texto:"Mis manos siguen siendo hábiles."},
{id:178,texto:"A veces, cuando estoy preocupado, comienzo a sudar, lo cual me molesta mucho."},
{id:179,texto:"No he tenido dificultades para mantener el equilibrio al caminar."},
{id:180,texto:"Algo no anda bien en mi cabeza."},
{id:181,texto:"No tengo accesos de alergia o asma."},
{id:182,texto:"He tenido ataques en los que perdía el control de mis movimientos o de la palabra, pero sabía lo que pasaba a mi alrededor."},
{id:183,texto:"Me desagradan algunas personas que conozco."},
{id:184,texto:"Muy pocas veces sueño despierto."},
{id:185,texto:"Me gustaría ser menos tímido."},
{id:186,texto:"No me da miedo manejar dinero."},
{id:187,texto:"Si fuera periodista me gustaría mucho informar sobre teatro."},
{id:188,texto:"Disfruto con muy diferentes clases de juegos y diversiones."},
{id:189,texto:"Me gusta flirtear (coquetear)."},
{id:190,texto:"Los míos me tratan más como a un niño que como a un adulto."},
{id:191,texto:"Me gustaría ser periodista."},
{id:192,texto:"Mi madre es una buena mujer (o lo fue si falleció)."},
{id:193,texto:"Cuando camino por la vereda evito cuidadosamente pisar las baldosas flojas."},
{id:194,texto:"Nunca he tenido erupciones en la piel que me hayan preocupado."},
{id:195,texto:"Comparando con otros hogares, en el mío hay poco amor o unión."},
{id:196,texto:"Con frecuencia, estoy preocupado por algo."},
{id:197,texto:"Creo que me gustaría el trabajo de contratista de obras."},
{id:198,texto:"Normalmente oigo voces sin saber de dónde vienen."},
{id:199,texto:"Me gusta la ciencia."},
{id:200,texto:"No me cuesta pedir ayuda a mis amigos, incluso aunque no pueda devolverles el favor."},
{id:201,texto:"Me gusta mucho cazar."},
{id:202,texto:"A menudo a mis padres les molestó el tipo de personas con las que me rodeaba."},
{id:203,texto:"A veces soy un poco chismoso."},
{id:204,texto:"Aparentemente escucho tan bien como las demás personas."},
{id:205,texto:"Alguno de mis familiares tiene costumbres que me molestan y fastidian muchísimo."},
{id:206,texto:"A veces me siento capaz de tomar decisiones con extraordinaria facilidad."},
{id:207,texto:"Me gustaría pertenecer a varios clubes o asociaciones."},
{id:208,texto:"Raramente noto los latidos de mi corazón y pocas veces se me corta la respiración."},
{id:209,texto:"Me gusta hablar sobre temas sexuales."},
{id:210,texto:"Me gusta visitar lugares donde nunca he estado."},
{id:211,texto:"Me han inspirado en un programa de vida basado en el deber y desde entonces lo he seguido cuidadosamente."},
{id:212,texto:"A veces he obstaculizado a personas, no porque importara demasiado sino por una cuestión de principios"},
{id:213,texto:"Me enojo fácilmente, pero se me pasa pronto."},
{id:214,texto:"He vivido bastante libre e independiente de las normas familiares."},
{id:215,texto:"Me preocupo muchísimo."},
{id:216,texto:"Alguien ha tratado de robarme."},
{id:217,texto:"Casi todos mis familiares simpatizan conmigo."},
{id:218,texto:"Hay momentos en que estoy tan nervioso que no puedo estar sentado mucho tiempo."},
{id:219,texto:"He tenido desengaños amorosos."},
{id:220,texto:"Nunca me preocupo por mi apariencia."},
{id:221,texto:"Sueño frecuentemente con cosas que es mejor guardarlas para mí mismo."},
{id:222,texto:"Debería enseñarse a los niños lo principal acerca de la vida sexual."},
{id:223,texto:"Creo que no soy más nervioso que la mayoría."},
{id:224,texto:"Tengo pocos o ningún dolor."},
{id:225,texto:"Mi modo de hacer las cosas tiende a ser mal interpretado por los demás."},
{id:226,texto:"A veces, sin razón alguna, incluso cuando las cosas van mal, me siento feliz, flotando entre nubes."},
{id:227,texto:"No culpo a nadie por tratar de apoderarse de todo lo que pueda en este mundo."},
{id:228,texto:"Hay personas que están intentando apoderarse de mis ideas y proyectos."},
{id:229,texto:"He tenido episodios en blanco que interrumpieron mis actividades, y en los que no sabía que ocurría a mí alrededor."},
{id:230,texto:"Puedo mostrarme amistoso con la gente que hace cosas que yo considero incorrectas."},
{id:231,texto:"Me gusta estar en un grupo en el que se hacen bromas mutuamente."},
{id:232,texto:"En las elecciones, algunas veces, voto candidatos que conozco muy poco."},
{id:233,texto:"Tengo dificultades para comenzar a hacer las cosas."},
{id:234,texto:"Siento que soy una persona condenada."},
{id:235,texto:"En el colegio era lento para aprender."},
{id:236,texto:"Si fuera artista me gustaría dibujar flores."},
{id:237,texto:"No me molesta ser poco elegante."},
{id:238,texto:"Transpiro muy fácilmente, incluso en días fríos."},
{id:239,texto:"Soy una persona plenamente segura de sí misma."},
{id:240,texto:"A veces me ha sido imposible vencer la tentación de robar."},
{id:241,texto:"Es más seguro no confiar en nadie."},
{id:242,texto:"Me excito mucho una vez por semana o con más frecuencia."},
{id:243,texto:"Cuando estoy con un grupo de gente, me altera tener que pensar temas adecuados de conversación."},
{id:244,texto:"Cuando estoy abatido, algo emocionante me saca casi siempre de ese estado."},
{id:245,texto:"Cuando salgo de casa no me preocupa si la puerta y las ventanas quedan bien cerradas."},
{id:246,texto:"Creo que mis pecados son imperdonables."},
{id:247,texto:"Tengo entumecimientos en una o más partes de mi piel."},
{id:248,texto:"No culpo a aquel que se aprovecha de otro que deja que se aprovechen de él."},
{id:249,texto:"Mi vista es tan buena como lo ha sido durante años."},
{id:250,texto:"A veces me ha divertido tanto el ingenio de un delincuente, que he deseado que le fuera bien."},
{id:251,texto:"A menudo me ha dado la sensación de que gente extraña me ha estado mirando con ojos críticos."},
{id:252,texto:"Todo tiene el mismo sabor o gusto."},
{id:253,texto:"Todos los días tomo una cantidad excesivamente grande de agua."},
{id:254,texto:"La mayor parte de la gente hace amigos porque es probable que le sean útiles."},
{id:255,texto:"casi nunca noto que me zumben o me chillen los oídos frecuentemente."},
{id:256,texto:"De vez en cuando siento odio hacia familiares que normalmente quiero."},
{id:257,texto:"Si fuera periodista me gustaría mucho informar sobre deportes."},
{id:258,texto:"Puedo dormir de día, pero no de noche."},
{id:259,texto:"Estoy seguro de que la gente habla de mí."},
{id:260,texto:"De cuando en cuando me divierten las bromas o chistes verdes."},
{id:261,texto:"Comparado con mis amigos, tengo muy pocos miedos."},
{id:262,texto:"Puedo iniciar una discusión, en un grupo de personas, sobre un tema que conozco."},
{id:263,texto:"Siento siempre aversión por la ley cuando un criminal sale libre gracias a la habilidad de un abogado astuto."},
{id:264,texto:"He abusado del alcohol."},
{id:265,texto:"Por lo general no le hablo a las personas hasta que ellas me hablan a mí."},
{id:266,texto:"Nunca he tenido problemas con la ley."},
{id:267,texto:"Tengo épocas en las que me he sentido más animado que de costumbre sin que exista una razón especial."},
{id:268,texto:"Me gustaría no ser perturbado por pensamientos sexuales."},
{id:269,texto:"Si varias personas se encuentran inculpadas, lo mejor que pueden hacer es ponerse de acuerdo en lo que van a decir y no cambiarlo después."},
{id:270,texto:"No me molesta ver sufrir a los animales."},
{id:271,texto:"Creo que mi sensibilidad es más intensa que la de la mayor parte de la gente."},
{id:272,texto:"En ningún momento de mi vida me ha gustado jugar con muñecas."},
{id:273,texto:"Para mí, la vida es tensión la mayor parte del tiempo."},
{id:274,texto:"Soy tan susceptible en algunos asuntos que no puedo hablar de ellos."},
{id:275,texto:"Me costaba mucho hablar delante de todos en el colegio."},
{id:276,texto:"Quiero a mi madre (o la quise sí falleció)."},
{id:277,texto:"Incluso cuando estoy con gente, me siento solo la mayor parte del tiempo."},
{id:278,texto:"Consigo todas las simpatías que debería."},
{id:279,texto:"Me niego a participar en algunos juegos porque no soy hábil en ellos."},
{id:280,texto:"Me parece que hago amigos tan rápido como los demás."},
{id:281,texto:"Me desagrada tener gente a mí alrededor."},
{id:282,texto:"Dicen que hablo cuando duermo."},
{id:283,texto:"Quien provoca la tentación dejando una cosa valiosa sin protegerla es tan culpable del robo como quien la roba."},
{id:284,texto:"Pienso que casi todo el mundo diría una mentira para evitar problemas."},
{id:285,texto:"Soy más sensible que la mayoría de la gente."},
{id:286,texto:"A la mayor parte de la gente le desagrada interiormente dejar lo suyo para ayudar a los demás."},
{id:287,texto:"Muchos de mis sueños son sobre temas sexuales."},
{id:288,texto:"Mis padres y familiares encuentran más defectos en mí de lo que deberían."},
{id:289,texto:"Me aturdo fácilmente."},
{id:290,texto:"Me preocupan el dinero y los negocios."},
{id:291,texto:"Nunca he estado enamorado de alguien."},
{id:292,texto:"Me han asustado ciertas cosas que han hecho algunos de mis familiares."},
{id:293,texto:"Casi nunca sueño."},
{id:294,texto:"A menudo me salen manchas rojas en el cuello."},
{id:295,texto:"Nunca he tenido parálisis ni sufrido una debilidad desacostumbrada en alguno de mis músculos."},
{id:296,texto:"Algunas veces pierdo o se me cambia la voz, incluso sin estar resfriado."},
{id:297,texto:"Mi padre o mi madre me obligaron frecuentemente a obedecer, incluso cuando yo pensaba que ello no era razonable."},
{id:298,texto:"A veces percibo olores extraños."},
{id:299,texto:"No puedo concentrarme en una sola cosa."},
{id:300,texto:"Tengo razones para sentirme celoso de uno o más de mis familiares."},
{id:301,texto:"Casi todo el tiempo siento ansiedad a causa de algo o alguien."},
{id:302,texto:"Me impaciento fácilmente con la gente."},
{id:303,texto:"Muchísimas veces me gustaría estar muerto."},
{id:304,texto:"Muchísimas veces me excito tanto que me cuesta dormirme por las noches."},
{id:305,texto:"Sin duda he tenido que preocuparme por más cosas que las que me correspondían."},
{id:306,texto:"Nadie parece comprenderme."},
{id:307,texto:"A veces oigo tan bien que me molesta."},
{id:308,texto:"Olvido enseguida lo que la gente me dice."},
{id:309,texto:"Normalmente tengo que pararme a pensar antes de actuar, incluso en asuntos sin importancia."},
{id:310,texto:"A menudo cruzo la calle para no encontrarme con alguna persona."},
{id:311,texto:"Con frecuencia siento como si las cosas no fueran reales."},
{id:312,texto:"La única parte interesante de los diarios es las páginas de los chistes."},
{id:313,texto:"Tengo la costumbre de contar con objetos sin importancia, como las bombillas de un letrero luminoso o cosas similares."},
{id:314,texto:"Carezco de enemigos que deseen realmente hacerme daño."},
{id:315,texto:"Tiendo a ponerme en guardia con aquellos que se muestran algo más amables de lo que yo esperaba."},
{id:316,texto:"Tengo pensamientos extraños y peculiares"},
{id:317,texto:"Me pongo ansioso e inquieto cuando tengo que hacer un viaje corto."},
{id:318,texto:"Normalmente espero tener éxito en las cosas que hago."},
{id:319,texto:"Oigo cosas extrañas cuando estoy solo."},
{id:320,texto:"He tenido miedo de cosas o personas que sabía que no podían hacerme daño."},
{id:321,texto:"No me da miedo entrar solo a una habitación donde hay gente reunida hablando."},
{id:322,texto:"Me da miedo utilizar cuchillos u objetos muy afilados o puntiagudos."},
{id:323,texto:"Algunas veces gozo con herir a personas que amo."},
{id:324,texto:"Me resulta fácil lograr que la gente me tenga miedo y eso me divierte."},
{id:325,texto:"Tengo más dificultad para concentrarme que la que otros parecen tener."},
{id:326,texto:"Varias veces he dejado de hacer algo por considerar insuficiente mi habilidad."},
{id:327,texto:"Se me ocurren palabras feas, a veces horribles, y no puedo dejarlas de lado."},
{id:328,texto:"Algunas veces me ronda en la cabeza un pensamiento sin importancia y me molesta durante días."},
{id:329,texto:"Casi a diario ocurre algo que me asusta."},
{id:330,texto:"A veces siento que me sobran energías."},
{id:331,texto:"Me inclino a tomar las cosas muy en serio."},
{id:332,texto:"A veces me ha gustado ser herido por una persona querida."},
{id:333,texto:"La gente dice de mi cosas insultantes y vulgares."},
{id:334,texto:"Me siento incómodo cuando estoy bajo techo (dentro de un edificio o habitación)."},
{id:335,texto:"Soy poco conciente de mi mismo."},
{id:336,texto:"Estoy seguro de que alguien controla mi mente."},
{id:337,texto:"En las fiestas y reuniones, en vez de unirme al grupo, es más probable que me siente solo o con otra persona."},
{id:338,texto:"La gente me decepciona con frecuencia."},
{id:339,texto:"Algunas veces me ha parecido que las dificultades se acumulaban de tal modo que no podía superarlas."},
{id:340,texto:"Me gusta mucho ir a bailar."},
{id:341,texto:"Durante ciertos períodos mi mente parece trabajar más despacio que de costumbre."},
{id:342,texto:"En micros, trenes, suelo conversar con extraños."},
{id:343,texto:"Me gustan los niños."},
{id:344,texto:"Me gusta jugar pequeñas cantidades de dinero."},
{id:345,texto:"Si me dieran la oportunidad, podría hacer cosas que beneficiarían mucho al mundo."},
{id:346,texto:"Con frecuencia me he encontrado con personas con reputación de expertas, pero que no eran mejores que yo."},
{id:347,texto:"Me siento fracasado cuando me hablan del éxito de alguien que conozco bien."},
{id:348,texto:"Con frecuencia pienso: Me gustaría volver a ser niño."},
{id:349,texto:"Nada me hace más feliz que estar solo."},
{id:350,texto:"Si me dieran la oportunidad podría ser un buen líder."},
{id:351,texto:"Me incomodan las anécdotas indecentes."},
{id:352,texto:"Normalmente la gente pide para sus propios derechos más respeto que el que da a los de otras personas."},
{id:353,texto:"Me gustan las reuniones sociales porque puedo estar con gente."},
{id:354,texto:"Trato de memorizar los cuentos divertidos para poder contárselos a otros."},
{id:355,texto:"Una o más veces en mi vida sentí que alguien me obligó a hacer cosas hipnotizándome."},
{id:356,texto:"Me resulta difícil abandonar una tarea una vez que la empecé."},
{id:357,texto:"Generalmente no me involucro en los chismes que cuentan los que me rodean."},
{id:358,texto:"A menudo han sentido celos de mis ideas porque no las pensaron antes."},
{id:359,texto:"Me encanta estar con mucha gente (recitales, manifestaciones)."},
{id:360,texto:"No me preocupa encontrarme con extraños."},
{id:361,texto:"Alguien ha tratado de influenciar mi mente."},
{id:362,texto:"He fingido estar enfermo para evitar hacer algo."},
{id:363,texto:"Mis preocupaciones tienden a desaparecer cuando me junto con amigos."},
{id:364,texto:"Tiendo a abandonar lo que estoy haciendo si me sale mal."},
{id:365,texto:"Me gusta que la gente conozca lo que realmente pienso."},
{id:366,texto:"He tenido períodos en los que me sentí tan lleno de fuerzas que no necesitaba dormir."},
{id:367,texto:"Siempre que sea posible evito estar en una multitud."},
{id:368,texto:"Trato de evitar situaciones de crisis o dificultad."},
{id:369,texto:"Me considero capaz de lograr lo que me propongo cuando otros creen que no vale la pena."},
{id:370,texto:"Me gustan las fiestas y reuniones sociales."},
{id:371,texto:"Muchas veces desee pertenecer al sexo opuesto."},
{id:372,texto:"No me enojo fácilmente."},
{id:373,texto:"He hecho algunas cosas malas en el pasado que no se las conté a nadie."},
{id:374,texto:"La mayoría de la gente puede hacer cosas incorrectas con tal de lograr su propósito."},
{id:375,texto:"Me pongo nervioso cuando la gente me hace preguntas personales."},
{id:376,texto:"Me siento incapaz de planificar mi futuro."},
{id:377,texto:"Me desagrada mi forma de ser."},
{id:378,texto:"Generalmente me enojo cuando amigos o familiares me dan consejos."},
{id:379,texto:"Me golpearon mucho cuando era chico."},
{id:380,texto:"Me molesto cuando la gente me elogia."},
{id:381,texto:"Me disgusta escuchar a la gente que da sus opiniones acerca de la vida."},
{id:382,texto:"A menudo he tenido desacuerdos serios con gente amiga."},
{id:383,texto:"Sé que puedo contar con la ayuda de mi familia cuando las cosas me van mal."},
{id:384,texto:"Me gustaba jugar a la mamá o al papá (o a las casitas) cuando era niño."},
{id:385,texto:"No le tengo miedo al fuego."},
{id:386,texto:"Muchas veces me he alejado de alguna persona por temor de decir o hacer algo de lo que después podría arrepentirme."},
{id:387,texto:"Sólo puedo expresar lo que realmente siento cuando bebo."},
{id:388,texto:"Rara vez tengo momentos de depresión."},
{id:389,texto:"Me han dicho con frecuencia que tengo mal carácter."},
{id:390,texto:"Desearía haber podido dejar de preocuparme por cosas que dije y que pudieron lastimar los sentimientos de algunas personas."},
{id:391,texto:"Me siento incapaz de contarle a alguien todas mis cosas."},
{id:392,texto:"Le tengo miedo a los relámpagos."},
{id:393,texto:"Me gusta que los demás estén intrigados acerca de lo que voy a hacer."},
{id:394,texto:"Frecuentemente mis proyectos me han parecido tan llenos de dificultades que he tenido que abandonarlos "},
{id:395,texto:"Me da miedo estar solo en la oscuridad."},
{id:396,texto:"Muchas veces me ha caído mal ser incomprendido cuando trataba de evitar que alguien se equivocara."},
{id:397,texto:"Le tengo miedo a las tormentas con mucho viento."},
{id:398,texto:"Frecuentemente pido consejos a otras personas."},
{id:399,texto:"El futuro es demasiado incierto para que una persona haga planes importantes."},
{id:400,texto:"A menudo, incluso cuando todo me sale bien, siento que nada me importa."},
{id:401,texto:"No le tengo miedo al agua."},
{id:402,texto:"A menudo tengo que consultar con la almohada, antes de tomar una decisión."},
{id:403,texto:"A menudo la gente ha interpretado mal mis intenciones cuando trataba de ayudarla."},
{id:404,texto:"No tengo dificultad al tragar."},
{id:405,texto:"Soy una persona tranquila y no me altero fácilmente."},
{id:406,texto:"Me gusta combatir a los criminales con sus propias armas."},
{id:407,texto:"Merezco un castigo severo por mis pecados."},
{id:408,texto:"Me tomo tan en serio las decepciones que me cuesta sacármelas de la cabeza."},
{id:409,texto:"Me molesta que alguien me observe cuando trabajo aunque sepa que lo hago bien."},
{id:410,texto:"A menudo me molesta tanto que alguien trate de adelantarse delante de mí en una cola, que tengo que decirle algo."},
{id:411,texto:"A veces pienso que no valgo para nada."},
{id:412,texto:"Cuando era chico frecuentemente salía para la escuela pero no llegaba a ella."},
{id:413,texto:"Uno o varios de mis familiares son muy nerviosos."},
{id:414,texto:"A veces he tenido que ser duro con personas groseras o inoportunas."},
{id:415,texto:"Me preocupo bastante por posibles desgracias."},
{id:416,texto:"Tengo opiniones políticas muy definidas."},
{id:417,texto:"Me gustaría ser corredor de automovilismo."},
{id:418,texto:"Es correcto bordear los límites de la Ley con tal de no violarla claramente."},
{id:419,texto:"Me desagradan tanto algunas personas, que me alegro interiormente cuando les llaman la atención por algo que han hecho."},
{id:420,texto:"Me pone nervioso tener que esperar."},
{id:421,texto:"Tiendo a dejar algo que deseo hacer porque otros piensan que lo encaro incorrectamente."},
{id:422,texto:"Cuando era joven me apasionaba lo emocionante."},
{id:423,texto:"Con frecuencia me esfuerzo para triunfar sobre alguien que se enfrenta a mí."},
{id:424,texto:"Me molesta que me mire gente desconocida, en el colectivo, en los negocios."},
{id:425,texto:"El hombre que más tuvo que ver conmigo cuando era niño (como mi padre, mi padrastro, etc.) fue muy rígido."},
{id:426,texto:"Cuando era niño, me gustaba jugar al rango (rayuela) y a la soga."},
{id:427,texto:"Nunca he tenido una visión."},
{id:428,texto:"Varias veces he cambiado de modo de pensar acerca de mi trabajo."},
{id:429,texto:"Nunca tomo drogas o pastillas para dormir, a no ser por orden del médico."},
{id:430,texto:"Frecuentemente lamento tener mal carácter o ser tan protestón."},
{id:431,texto:"En la escuela, mis calificaciones en conducta fueron generalmente malas."},
{id:432,texto:"Me fascina el fuego."},
{id:433,texto:"Cuando estoy en una situación difícil sólo digo aquella parte de la verdad que probablemente no me va a perjudicar."},
{id:434,texto:"Si estuviera en dificultades junto con varios amigos que fueran tan culpables como yo, preferiría echarme la culpa antes que descubrirlos."},
{id:435,texto:"A menudo tengo miedo a la oscuridad."},
{id:436,texto:"Cuando un hombre está con una mujer, generalmente está pensando cosas relacionadas con el sexo de ella."},
{id:437,texto:"Generalmente le hablo claro a la gente que estoy intentando corregir o mejorar."},
{id:438,texto:"Me aterroriza la idea de un terremoto."},
{id:439,texto:"Rápidamente me convenzo por completo de una buena idea."},
{id:440,texto:"Generalmente hago las cosas por mí mismo, en vez de buscar a alguien que me diga como hacerlas."},
{id:441,texto:"Siento miedo cuando estoy en un lugar pequeño y cerrado."},
{id:442,texto:"Admito que a veces me he preocupado sin motivo alguno por cosas que no valían la pena."},
{id:443,texto:"No trato de disimular mi pobre opinión o lástima sobre algunas personas."},
{id:444,texto:"Soy una persona de una gran tensión."},
{id:445,texto:"Frecuentemente he trabajado a las órdenes de personas que parecen haber arreglado las cosas de tal modo, que ellas son las que reciben el reconocimiento de una buena labor y, en cambio, atribuyen los errores a sus subordinados."},
{id:446,texto:"A veces me es difícil defender mis derechos por ser tan reservado."},
{id:447,texto:"La suciedad me espanta o me disgusta."},
{id:448,texto:"Vivo una vida de ensueños, acerca de la cual no digo nada a nadie."},
{id:449,texto:"Algunos de mis familiares tienen mal carácter."},
{id:450,texto:"No puedo hacer bien ninguna cosa."},
{id:451,texto:"A menudo me he sentido culpable porque he fingido mayor sufrimiento del que realmente sentía."},
{id:452,texto:"Por regla general defiendo con tenacidad mis opiniones."},
{id:453,texto:"No temo a las arañas."},
{id:454,texto:"Para mí el futuro carece de esperanza."},
{id:455,texto:"Mis familiares y parientes más cercanos se llevan bastante bien."},
{id:456,texto:"Me gustaría tener ropa cara."},
{id:457,texto:"La gente puede hacerme cambiar de opinión muy fácilmente, incluso en materias en las que creía tener ya un criterio firme."},
{id:458,texto:"Ciertos animales me ponen nervioso."},
{id:459,texto:"Puedo soportar tanto dolor como los demás."},
{id:460,texto:"Varias veces he sido el último en darme por vencido al tratar de hacer algo."},
{id:461,texto:"Me pone de mal humor que la gente me apure."},
{id:462,texto:"No tengo miedo a los ratones."},
{id:463,texto:"Varias veces a la semana siento como si fuera a suceder algo espantoso."},
{id:464,texto:"Me siento cansado una buena parte del tiempo."},
{id:465,texto:"Me gusta arreglar las cerraduras de las puertas."},
{id:466,texto:"Algunas veces estoy seguro de que otro puede decir lo que estoy pensando."},
{id:467,texto:"Me gusta leer temas científicos."},
{id:468,texto:"Temo estar solo en lugares amplios y abiertos."},
{id:469,texto:"Algunas veces me siento al borde de una crisis nerviosa."},
{id:470,texto:"Un gran número de personas tienen mala conducta sexual."},
{id:471,texto:"A menudo he sentido miedo en plena noche."},
{id:472,texto:"Me molesta mucho olvidarme donde pongo las cosas."},
{id:473,texto:"La persona hacia quien sentía más afecto y admiración cuando era niño, fue una mujer (madre, hermana, tía u otra mujer)."},
{id:474,texto:"Me gustan más las historias de aventuras que las románticas."},
{id:475,texto:"A veces me confundo y olvido lo que quiero decir."},
{id:476,texto:"Soy muy torpe y pesado."},
{id:477,texto:"Me gustan los deportes fuertes como el fútbol o rugby."},
{id:478,texto:"Detesto a toda mi familia."},
{id:479,texto:"Algunas personas piensan que es difícil conocerme, saber como soy."},
{id:480,texto:"Paso la mayor parte de mi tiempo libre a solas."},
{id:481,texto:"Cuando la gente hace cosas que me enfurencen se los hago saber"},
{id:482,texto:"Me cuesta tomar decisiones."},
{id:483,texto:"La gente no me ve como una persona atractiva."},
{id:484,texto:"La gente es poco amable conmigo."},
{id:485,texto:"A veces siento que no soy tan bueno como los demás."},
{id:486,texto:"Soy cabeza dura."},
{id:487,texto:"Me gustó fumar marihuana."},
{id:488,texto:"La enfermedad mental es signo de debilidad."},
{id:489,texto:"Tengo problemas con la droga o el alcohol."},
{id:490,texto:"Los fantasmas o espíritus influyen en la vida de las personas, para bien o para mal."},
{id:491,texto:"Me siento desamparado cuando tengo que decidir algo importante."},
{id:492,texto:"Siempre trato de ser agradable aún cuando los otros están molestos o son críticos."},
{id:493,texto:"Cuando tengo un problema me ayuda el contárselo a otra persona."},
{id:494,texto:"Las principales metas de mi vida están a mi alcance"},
{id:495,texto:"Creo que la gente debe guardarse sus problemas personales."},
{id:496,texto:"No estoy sintiendo mucha presión o estrés por éstos días"},
{id:497,texto:"Me molesta grandemente pensar en hacer cambios en mi vida."},
{id:498,texto:"Mis mayores problemas son causados por la manera de actuar de alguien cercano"},
{id:499,texto:"Detesto ir al médico aún cuando estoy enfermo."},
{id:500,texto:"Aunque soy poco feliz, no puedo hacer nada para modificarlo."},
{id:501,texto:"Hablar de los problemas o preocupaciones con alguien es más útil que tomar remedios para resolverlos."},
{id:502,texto:"Tengo algunos hábitos que son realmente perjudiciales."},
{id:503,texto:"Si hay que resolver un problema, le dejo la iniciativa a los demás."},
{id:504,texto:"Reconozco muchos errores en mí que no soy capaz de cambiar."},
{id:505,texto:"Me disgusta tanto lo que hago diariamente que quisiera dejar de hacerlo."},
{id:506,texto:"Recientemente he pensado en suicidarme."},
{id:507,texto:"Realmente me enojo cuando interrumpen mi trabajo."},
{id:508,texto:"A menudo siento que puedo leer lo que otros están pensando."},
{id:509,texto:"Me pongo nervioso cuando tengo que tomar una decisión importante."},
{id:510,texto:"Dicen que como muy rápido."},
{id:511,texto:"Por lo menos una vez por semana me emborracho o me drogo."},
{id:512,texto:"Tuve una pérdida afectiva importante en mi vida que no puedo superar."},
{id:513,texto:"A veces me enojo tanto que no sé lo que digo o hago."},
{id:514,texto:"Me cuesta decir que no cuando me piden que haga algo."},
{id:515,texto:"Sólo soy feliz cuando estoy solo."},
{id:516,texto:"Mi vida es vacía y sin sentido."},
{id:517,texto:"Me cuesta conservar un trabajo."},
{id:518,texto:"Cometí muchos errores en mi vida."},
{id:519,texto:"Me enojo conmigo mismo por ser tan generoso con los demás."},
{id:520,texto:"Ultimamente he pensado mucho en quitarme la vida."},
{id:521,texto:"Me agrada tomar decisiones and assigning jobs to others."},
{id:522,texto:"Aunque me quedara sin familia sé que siempre habrá alguien para cuidarme."},
{id:523,texto:"Me disgusta tener que hacer colas en cines teatros o restaurantes."},
{id:524,texto:"Nadie lo sabe pero intenté suicidarme."},
{id:525,texto:"Todo pasa muy rápido a mi alrededor."},
{id:526,texto:"Sé que le resulto pesado a la gente."},
{id:527,texto:"Después de un mal día, necesito tomar unos tragos para poder relajarme."},
{id:528,texto:"Muchos de mis problemas se deben a mi mala suerte."},
{id:529,texto:"A veces me resulta difícil dejar de hablar."},
{id:530,texto:"A veces me corto o lastimo a mí mismo sin saber por qué."},
{id:531,texto:"Trabajo muchas horas sin que ello sea necesario."},
{id:532,texto:"Generalmente me siento mejor después de llorar."},
{id:533,texto:"Me olvido donde dejo las cosas."},
{id:534,texto:"Si volviera a nacer no cambiaría mucho"},
{id:535,texto:"Me pone de mal humor que la gente con la que trabajo no haga las cosas a tiempo."},
{id:536,texto:"Si tengo un disgusto seguramente tendré dolor de cabeza"},
{id:537,texto:"Me gusta manejar autos viejos."},
{id:538,texto:"La mayoría de los hombres es infiel a sus esposas de vez en cuando"},
{id:539,texto:"Ultimamente, perdí las ganas de preocuparme por mis problemas."},
{id:540,texto:"Hubo ocasiones en las que me enojé y rompí cosas por haber bebido mucho."},
{id:541,texto:"Trabajo mejor cuando tengo plazos bien definidos."},
{id:542,texto:"He llegado a enfurecerme tanto con alguien que creí que iba a estallar."},
{id:543,texto:"A veces me vienen pensamientos terribles sobre mi familia."},
{id:544,texto:"La gente me dice que tengo problemas con el alcohol, pero yo no estoy de acuerdo."},
{id:545,texto:"Siempre tengo poco tiempo para poder hacer las cosas que debo."},
{id:546,texto:"Ultimamente, pienso mucho en la muerte y el más allá."},
{id:547,texto:"Guardo cosas que nunca uso."},
{id:548,texto:"He estado tan furioso que llegué a golpear y lastimar a una persona."},
{id:549,texto:"En todo lo que hago, siento que me están tomando examen."},
{id:550,texto:"Estoy bastante alejado de mis familiares actualmente."},
{id:551,texto:"A veces siento que escuchan los que estoy pensando."},
{id:552,texto:"Cuando estoy triste, me hace bien visitar amigos."},
{id:553,texto:"Siento que lo que me está pasando ahora ya me sucedió antes."},
{id:554,texto:"Cuando mi vida se pone difícil siento simplemente ganas de rendirme"},
{id:555,texto:"Me da miedo entrar a una habitación oscura, aún en mi propia casa."},
{id:556,texto:"Me preocupo mucho por el dinero."},
{id:557,texto:"El hombre debe ser la cabeza de la familia."},
{id:558,texto:"Sólo me siento relajado en mi casa."},
{id:559,texto:"Mis compañeros de trabajo entienden muy poco mis problemas."},
{id:560,texto:"Estoy conforme con el dinero que gano."},
{id:561,texto:"Generalmente tengo suficiente energía para cumplir con mis tareas."},
{id:562,texto:"Me resulta difícil aceptar elogios."},
{id:563,texto:"En la mayoría de los matrimonios, una de las personas o ambas son poco felices."},
{id:564,texto:"Casi nunca pierdo el control."},
{id:565,texto:"Por éstos días me cuesta mucho esfuerzo recordar lo que me dicen."},
{id:566,texto:"Cuando estoy triste o mal, es mi trabajo el que sufre"},
{id:567,texto:"La mayor parte de los matrimonios no se demuestran mucho afecto"}


]